### ISSUE TITLE
Craftman composer - environment issues

### ISSUE THREAD

**Issue by sampnorris** [HatchWD/craftman#1]
When craftman creates a new install, It runs a composer script outside of docker, 
Environment issues happen if composer isn't installed or php is less than 7.

We need to use composer that is already installed in 
`./scripts/composer.phar`
to run from inside the docker container on initialisation of a new project && on `craftman start`.
This needs to be run inside the directory `/var/www` where composer.json is sitting.

Work around is to run
`craftman run`
then
`cd /var/www` 
then run
`../../scripts/composer.phar install`

This will install craft on the newly cloned repo if composer cannot be run from the host computer.

**Comment by codyyc** [comment]
Really nice and thorough!

**Comment by codyyc** [comment]
This is now resolved with the ``craft_init() `` command.
